
# Aula 4 - Introdução ao NumPy

Nesta aula, vamos explorar a biblioteca **NumPy**, amplamente utilizada em Python para computação numérica eficiente. Vamos abordar os seguintes tópicos:

- Criação de arrays.
- Operações matemáticas com arrays.
- Funções universais e manipulação de matrizes.

Além disso, teremos exemplos adicionais e alguns mini exercícios para praticar.

---

## Instalando o NumPy

Se ainda não tiver o NumPy instalado, você pode rodar o seguinte comando:

```bash
pip install numpy
```


## NumPy e Arrays

A estrutura de dados central do NumPy é o **array**. Arrays são semelhantes às listas em Python, porém mais eficientes e poderosos, especialmente ao lidar com operações numéricas.

Vamos começar criando nossos primeiros arrays com NumPy.



### Criando Arrays

Existem várias formas de criar arrays em NumPy:

- **`np.array()`**: Cria um array a partir de uma lista ou tupla.
- **`np.zeros()`**: Cria um array preenchido com zeros.
- **`np.ones()`**: Cria um array preenchido com uns.
- **`np.arange()`**: Cria um array com uma sequência de números.
- **`np.linspace()`**: Cria um array de números igualmente espaçados em um intervalo.

#### Exemplo:


In [8]:
# Importando o NumPy
import numpy as np

# Criando arrays de diferentes maneiras
array1 = np.array([1, 2, 3, 4])
array2 = np.zeros((2, 3))
array3 = np.ones((3, 3))
array4 = np.arange(0, 10, 2)
array5 = np.linspace(0, 1, 5)

# Exibindo os arrays
print("Array a partir de lista:", array1)
print("Array de zeros:\n", array2)
print("Array de uns:\n", array3)
print("Array com arange:\n", array4)
print("Array com linspace:\n", array5)

Array a partir de lista: [1 2 3 4]
Array de zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array de uns: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array com arange: [0 2 4 6 8]
Array com linspace: [0.   0.25 0.5  0.75 1.  ]



#### **exercício 1:**
Crie um array de 20 números igualmente espaçados entre 0 e 5.



## Operações Matemáticas com Arrays

NumPy permite realizar operações matemáticas de forma vetorizada, ou seja, operações que são aplicadas diretamente a todos os elementos do array de uma só vez. Isso torna as operações muito mais rápidas do que se fossem realizadas elemento por elemento.

Você pode realizar operações como:

- Adição, subtração, multiplicação e divisão de arrays.
- Operações de agregação como soma, média e desvio padrão.

#### Exemplo de operações:


In [10]:
# Operações matemáticas com arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Operações elementares
soma = a + b
produto = a * b
divisao = b / a

# Operações de agregação
soma_total = np.sum(a)
media = np.mean(b)
desvio_padrao = np.std(b)

# Exibindo os resultados
print("Soma dos arrays:", soma)
print("Produto dos arrays:", produto)
print("Divisão dos arrays:", divisao)
print("Soma total do array a:", soma_total)
print("Média do array b:", media)
print("Desvio padrão do array b:", desvio_padrao)

Soma dos arrays: [11 22 33 44]
Produto dos arrays: [ 10  40  90 160]
Divisão dos arrays: [10. 10. 10. 10.]
Soma total do array a: 10
Média do array b: 25.0
Desvio padrão do array b: 11.180339887498949



#### **Mini exercício 2:**
Dado o array `arr = np.array([5, 10, 15, 20, 25])`, calcule a média e o desvio padrão dos valores.


In [ ]:
# Resposta Mini exercício 2
arr = np.array([5, 10, 15, 20, 25])
media_arr = np.mean(arr)
desvio_padrao_arr = np.std(arr)

print("Média do array:", media_arr)
print("Desvio padrão do array:", desvio_padrao_arr)


## Funções Universais

NumPy oferece **funções universais** (ou **ufuncs**), que são funções vetorizadas e aplicadas elemento a elemento em arrays. Exemplos incluem funções trigonométricas, exponenciais, logarítmicas, entre outras.

#### Exemplo de funções universais:


In [11]:
# Exemplo de funções universais
array = np.array([1, 2, 3, 4])

# Aplicando funções universais
log_array = np.log(array)
exp_array = np.exp(array)
sin_array = np.sin(array)

# Exibindo os resultados
print("Logaritmo:", log_array)
print("Exponencial:", exp_array)
print("Seno:", sin_array)

Logaritmo: [0.         0.69314718 1.09861229 1.38629436]
Exponencial: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]



#### **Mini exercício 3:**
Dado o array `x = np.array([1, 2, 3, 4, 5])`, aplique a função seno (np.sin) a todos os elementos.


In [ ]:
# Resposta Mini exercício 3
x = np.array([1, 2, 3, 4, 5])
seno_x = np.sin(x)
print("Seno de cada elemento:", seno_x)


## Manipulação de Matrizes

Além de arrays unidimensionais (vetores), NumPy também permite trabalhar com **matrizes** (arrays multidimensionais). É possível realizar operações como transposição, reshape e indexação.

### Operações com Matrizes:
- **`reshape()`**: Redimensiona o array.
- **`transpose()`**: Transpõe o array (troca linhas por colunas).
- **Indexação e fatiamento**: Acessa elementos ou subconjuntos de um array.

#### Exemplo de manipulação de matrizes:


In [4]:
import numpy as np
# Criando uma matriz (array 2D)
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Transpondo a matriz
matriz_transposta = matriz.T

# Redimensionando a matriz
matriz_reshaped = matriz.reshape(3, 2)

# Indexação e fatiamento
elemento = matriz[0, 1]  # Elemento na linha 0, coluna 1
submatriz = matriz[:, 1:]  # Todas as linhas, colunas 1 e 2

# Exibindo os resultados
print("Matriz original:")
print(matriz)
print("Matriz transposta:")
print(matriz_transposta)
print("Matriz redimensionada:")
print(matriz_reshaped)
print("Elemento na posição [0,1]:", elemento)
print("Submatriz (colunas 1 e 2):")
print(submatriz)

Matriz original:
[[1 2 3]
 [4 5 6]]
Matriz transposta:
[[1 4]
 [2 5]
 [3 6]]
Matriz redimensionada:
[[1 2]
 [3 4]
 [5 6]]
Elemento na posição [0,1]: 2
Submatriz (colunas 1 e 2):
[[2 3]
 [5 6]]



#### **Mini exercício 4:**
Crie uma matriz 3x3 com números consecutivos de 1 a 9. Em seguida, extraia a submatriz que contém os elementos das duas primeiras colunas.


In [12]:
# Resposta Mini exercício 4
matriz_exercicio = np.arange(1, 10).reshape(3, 3)
submatriz_exercicio = matriz_exercicio[:, :2]

print("Matriz 3x3:")
print(matriz_exercicio)
print("Submatriz (duas primeiras colunas):")
print(submatriz_exercicio)

Matriz 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Submatriz (duas primeiras colunas):
[[1 2]
 [4 5]
 [7 8]]
